files:
  - source: /**/values/*.xml
    translation: /**/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        es-ES: es-es-es
  - source: /**/values/*.xliff
    translation: /**/values-%two_letters_code%/%original_file_name%
